Development
kristinavlasovets/date-picker pull request #1
Opened 2023-06-01 07:25 UTC by kristinavlasovets

2023-06-02 08:15 UTC, anyaprystavka requested changes

2023-06-02 08:15 UTC, anyaprystavka commented on .eslintrc
> +  },
в eslint необходимо добавить плагин [airnbnb](https://www.npmjs.com/package/eslint-config-airbnb), который предоставляет правила для написания кода

2023-06-02 08:15 UTC, anyaprystavka commented on package.json
> +    "@babel/preset-env": "^7.21.5",
нужно пересмотреть все зависимости, что относится к  dependencies, что к devDependencies - это очень важно и этого нужно придерживаться всегда

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Button/index.ts
> +export { default } from './Button';
в тестовом задании необходимо придерживаться той структуры, которая дана по ТЗ, поэтому в файле index.tsx должен находиться сам компонент и так во всем приложении

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Button/styles.ts
> +  font-family: 'Open Sans', sans-serif;
шрифт обязательно в общей теме хранится

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +import Button from '../Button/Button';
из-за текущей организации структуры папки компонента, путь Button/Button выглядит не очень

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +import { GlobalStyles } from '@/styles/globalStyles';
вот для таких случаев, когда нужно что-то импортировать из одной папки, но с разных файлов, в папке создается файл index.ts, из которого все импортируется, это сокращает код при импортировании данных

2023-06-02 08:15 UTC, anyaprystavka commented on src/index.ts
> +export * from './components';
в конечном итоге, все что ты импортируешь с этого файла, должно использоваться в другом проекте, где ты свою библиотеку будешь применять, поэтому импортируй только то, что тебе понадобится

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/styles.ts
> +  z-index: 10;
z-index тоже выноси в общую тему для стилей

2023-06-02 08:15 UTC, anyaprystavka commented on src/constants/config/holidays.ts
> +  new Date(2023, 8, 17),
отображение праздников должно быть на каждый год

2023-06-02 08:15 UTC, anyaprystavka commented on src/constants/config/components/button/index.ts
> +  text: 'Clear',
для констант можно использовать enum

2023-06-02 08:15 UTC, anyaprystavka commented on src/constants/config/components/calendar/index.ts
> +export const calendarText = {
то, что ты логически выносишь константы в зависимости от компонента - хорошо, это понятно, но создание файла - это ресурс памяти и в самих файлах практически присутствует только один тип, который экспортится, поэтому это избыточно

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +import MyCloseSvg from '../../assets/icons/close.svg';
важно, чтобы везде были использованы алиасы в импортах

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +    const t = localStorage.getItem(`${selectedDate.getTime()}todos`);
названия переменным необходимо давать осмысленные, чтобы было понятно за что они отвечают

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +  useEffect(() => {
работа с localStorage - это можно вынести отдельно в хелперскую функцию

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +          <TodoItem
вот этот компонент(всю папку с компонентом) в структуре папки components можно поместить в папку текущего компонента - TodoList. Это значит, что TodoItem применяется только в TodoList

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/RangePicker/RangePicker.tsx
> +      <GlobalStyles theme={commonTheme} />
не очень понятно почему ты пробрасываешь commonTheme в GlobalStyles

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/RangePicker/RangePicker.tsx
> +  const withoutTodo = true;
вот тут не очень понятно почему ты здесь пишешь константу и еще ее прокидываешь в компонент

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +    <ThemeProvider theme={commonTheme}>
в ThemeProvider ты обернула компонент, в котором используешь компонент Calendar, поэтому избыточно его еще раз оборачивать в ThemeProvider и GlobalStyles

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +  const onHandlerSelectDate = (
обычно, когда функция пробрасывается в props дочернего компонента - можно использовать хук useCallback, чтобы при ререндере в случае создания нового экземпляра - этого не происходило, если в функции ничего не поменялось

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGridByMonth/CalendarGridByMonth.tsx
> +  currentYear,
вот тут не очень понятно, почему ты создаешь еще один компонент, в котором просто прокидываешь входящие пропсы в компонент - это избыточно

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGridByWeek/CalendarGridByWeek.tsx
> +        {`${currentWeek + 1} / ${Math.ceil(totalDays.length / 7)}`}
где используется Math - значение еще раз пересчитывается при ререндере и не очень понятно, что это за значение, на которое ты делишь, поэтому лучше вынести его выше и мемоизировать

2023-06-02 08:15 UTC, anyaprystavka commented on src/utils/decorators/CalendarByMonthDecorator.tsx
> +export const CalendarByMonthDecorator = (
сам паттерн должен представлять один общий интерфейс оберток и передавать оборачиваему компоненту всю свою логику, которая есть в нем(конкретно для компонента, так как в обертке может быть и другая логика для других компонентов), в свою очередь это могут быть конкретные декораторы, которые содержат определенную логику

2023-06-02 08:15 UTC, anyaprystavka commented on src/utils/helpers/CalendarHelpers.ts
> +export const getNumberOfDaysinMonth = (year: number, month: number) => {
везде camelCase

2023-06-02 08:15 UTC, anyaprystavka commented on src/utils/helpers/CalendarHelpers.ts
> +  const length = Math.abs((end - start) / 1);
зачем тут деление на единицу?

2023-06-02 08:15 UTC, anyaprystavka commented on src/utils/helpers/CalendarHelpers.ts
> +interface GetDayVariantProps {
интерфейс нужно вынести

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Day/styles.ts
> +const DayItemVariants = {
вот тут этот объект можно вынести в константу или config

2023-06-02 08:15 UTC, anyaprystavka commented on src/utils/decorators/CalendarByMonthDecorator.tsx
> +export const CalendarByMonthDecorator = (
сам HOC - действительно может являться декоратором, но только в том случае, когда он наделяется входящий компонент логикой - в данном случае он просто прокидывает пропсы, который прокинуты выше - это не является реализацией паттерна декторатор

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +  minDate,
проблема, на которую всегда нужно обращать внимание - props-drilling, в приложение много где эта проблема есть, поэтому одно из решений - это context

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +  $holidayColor,
в приложении встречаются переменный, которые начинаются с $, похоже на смесь синтаксиса с php, но не очень понятно почему они начинаются с $

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +  const [selectedDate, setSelectedDate] = useState<Date>(defaultValue);
также проблема большого количества состояний - это может решить следующий образом - объединение в одном useState логически связанных состояний

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +  const onHadlerChosenMonth = (
немного наводит на мысль: почему столько хендлеров в компоненте. можно ли тут объеденить по смыслу несколько функций в одну ?

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +    setIsYearPopup(!isYearPopup);
всегда изменение состояния, где меняется логическое значение - изменяется на основании предыдущего значения

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/Calendar.tsx
> +          {variant !== 'month' && isTodoList && !withoutTodo && (
вот тут какая-то проверка, чтобы точно удостоверится, что все работает:
isTodoList и withoutTodo являются по смыслу одним и тем же, поэтому тут не нужна дополнительная проверка

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/Calendar/styles.ts
> +  width: ${({ theme }) => theme.width.xl}%;
в приложении не желательно вообще использовать проценты и px, всегда что-то одной - это может влиять на адаптивную верстку. в случае с библиотекой - этого тоже надо придерживаться

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGrid/CalendarGrid.tsx
> +                (minDate &&
вот это условие очень странно выглядит, нужно подумать как его написать так, чтобы было более читабельно

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGridByMonth/CalendarGridByMonth.tsx
> +  showWeekend,
вот тут прослеживается явное прокидывание пропсов - проблема props-drilling

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGridByWeek/CalendarGridByWeek.tsx
> +      currentWeek * 7,
7 - магическое число, таких чисел не должно быть в проекте

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGridByWeek/CalendarGridByWeek.tsx
> +    ) as number[];
с as нужно быть аккуратным - не всегда это хорошая практика

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/CalendarGridByWeek/CalendarGridByWeek.tsx
> +        {`${currentWeek + 1} / ${Math.ceil(totalDays.length / 7)}`}
7 - магическое число

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/DateSelector/DateSelector.tsx
> +  const { calendarAlt, inputType, placeholder, clearAlt } = dateSelectorText;
вот  эту деструктуризацию можно вынести выше в коде, даже за компонентом - потому что это не приходит с пропсов, а является константой

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/DateSelector/DateSelector.tsx
> +      setErrorMessage('Incorrect data. Please, use dd/mm/yyyy format.');
'Incorrect data...' - можно вынести как константу

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/DayPicker/DayPicker.tsx
> +    setIsPopup(!isPopup);
изменение должно быть на основании предыдущего значения

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/DayPicker/DayPicker.tsx
> +          <Title>{title ? title : titleDefault}</Title>
вот тут title дублируется и можно использовать либо || для проверки значения, либо ??

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoItem/styles.ts
> +    completed === 'true' ? 'line-through' : 'none'};
вот такая проверка на строковое true является очень странной, почему именно строка?

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +  const [todos, setTodos] = useState<ITodoItem[]>([] as ITodoItem[]);
если ты типизируешь с помощью дженерика массив, зачем тогда еще раз с помощью as?

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +  const toggleCompleted = (id: number) => {
вот тут не очень понятно, почему применяется фильтр

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +        JSON.parse(t).filter(
не очень понятно зачем тут дополнительная проверка идет, если ты уже достала данные с LocalStorage

2023-06-02 08:15 UTC, anyaprystavka commented on src/components/TodoList/TodoList.tsx
> +        todos.map(({ id, title, completed }) => (
вот здесь в пр вижу, что вместо map - filter(стоит пересмотреть этот момент и всегда для простой отрисовки использовать map)

2023-06-02 08:15 UTC, anyaprystavka commented on .eslintignore
> +CalendarByWeekDecorator.tsx
вот так точно не стоит делать, если есть конфликты с eslint, то необходимо настраивать правила в конфигурации eslint

2023-06-02 08:15 UTC, anyaprystavka commented on src/constants/config/components/calendar/index.ts
> +export const calendarText = {
все константы, что хранятся в папке config - можно сделать проще и вынести все в один файл

2023-06-02 08:15 UTC, anyaprystavka commented on src/constants/styles/colors.ts
> +export enum Colors {
ты вынесла это в константы, в большей степени это именно тип, который содержит константы, поэтому лучше вынести это в types папку

2023-06-04 13:03 UTC, kristinavlasovets commented on src/components/RangePicker/RangePicker.tsx
> +  const withoutTodo = true;
этим я определяю что в компоненте RangePicker я я использую DayPicker без отображения TodoList

2023-06-04 15:36 UTC, kristinavlasovets commented on src/components/Calendar/Calendar.tsx
> +  $holidayColor,
При использовании textColor (или holidayColor) без знака $ возникала ошибка: 

React does not recognize the `textColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textсolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Я нашла решение проблемы таким образом

2023-06-04 16:25 UTC, kristinavlasovets commented on src/components/TodoList/TodoList.tsx
> +        JSON.parse(t).filter(
с localStorage может возвращаться и null, поэтому используя TypeScript, думаю лучше сделать такую проверку

иначе для currentTodos выдает ошибку: Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.ts(2345)

2023-06-05 11:11 UTC, kristinavlasovets commented on src/components/CalendarGridByMonth/CalendarGridByMonth.tsx
> +  currentYear,
Убрала два компонента CalendarGridByMonth и CalendarGridByWeek

2023-06-05 11:16 UTC, kristinavlasovets commented on src/utils/decorators/CalendarByMonthDecorator.tsx
> +export const CalendarByMonthDecorator = (
Убрала два декоратора (которые прокидывали пропсы) и два соответствующих компонента CalendarGridByMonth и CalendarGridByWeek.

Создала один общий декоратор HOC CalendarDecorator, который передает оборачиваемому компоненту (CalendarGrid) логику в зависимости от выбранного типа календаря.

2023-06-09 13:30 UTC, anyaprystavka approved these changes

2023-06-09 13:33 UTC, merged